spring.application.name=mercadona-backend

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5441/mercadona_db
server.port=8082
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
