CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL UNIQUE CHECK (source_id > 0),
    name text NOT NULL,
    category text NOT NULL,
    subtitle text NOT NULL,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    discount_price numeric(10,2) CHECK (discount_price >= 0),
    main_image_url text,
    secondary_image_url text,
    nutritional_info text,
    active boolean NOT NULL DEFAULT true,
    drink_eligible boolean NOT NULL DEFAULT false,
    dessert_eligible boolean NOT NULL DEFAULT false,
    serving_price numeric(10,2) CHECK (serving_price >= 0),
    serving_format text,
    CHECK (NOT (drink_eligible OR dessert_eligible) OR (serving_price IS NOT NULL AND serving_format IS NOT NULL))
);
CREATE INDEX product_drinks_idx ON product (name) WHERE drink_eligible AND active;
CREATE INDEX product_desserts_idx ON product (name) WHERE dessert_eligible AND active;

CREATE TABLE dish (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(100) NOT NULL UNIQUE,
    name text NOT NULL,
    description text NOT NULL,
    image_url text,
    base_price numeric(10,2) NOT NULL CHECK (base_price >= 0),
    active boolean NOT NULL DEFAULT true
);
CREATE TABLE dish_ingredient (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id bigint NOT NULL REFERENCES dish (id),
    product_id bigint NOT NULL REFERENCES product (id),
    default_quantity integer NOT NULL,
    min_quantity integer NOT NULL,
    max_quantity integer NOT NULL,
    step_quantity integer NOT NULL CHECK (step_quantity > 0),
    unit varchar(16) NOT NULL CHECK (unit IN ('G', 'ML', 'UNIT')),
    extra_step_price numeric(10,2) NOT NULL CHECK (extra_step_price >= 0),
    position integer NOT NULL CHECK (position >= 0),
    UNIQUE (dish_id, product_id),
    CHECK (min_quantity >= 0 AND min_quantity <= default_quantity AND default_quantity <= max_quantity),
    CHECK (min_quantity % step_quantity = 0 AND default_quantity % step_quantity = 0 AND max_quantity % step_quantity = 0)
);
CREATE INDEX dish_ingredient_product_idx ON dish_ingredient (product_id);

CREATE TABLE cart (
    id uuid PRIMARY KEY,
    token_hash varchar(64) NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE TABLE cart_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id uuid NOT NULL REFERENCES cart (id),
    dish_id bigint NOT NULL REFERENCES dish (id),
    dish_name text NOT NULL,
    quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    base_price numeric(10,2) NOT NULL CHECK (base_price >= 0),
    ingredient_extras numeric(10,2) NOT NULL CHECK (ingredient_extras >= 0),
    drink_price numeric(10,2) NOT NULL CHECK (drink_price >= 0),
    dessert_price numeric(10,2) NOT NULL CHECK (dessert_price >= 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price = base_price + ingredient_extras + drink_price + dessert_price)
);
CREATE INDEX cart_item_cart_idx ON cart_item (cart_id);
CREATE INDEX cart_item_dish_idx ON cart_item (dish_id);
CREATE TABLE cart_item_ingredient (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_item_id bigint NOT NULL REFERENCES cart_item (id),
    dish_ingredient_id bigint NOT NULL REFERENCES dish_ingredient (id),
    product_id bigint NOT NULL REFERENCES product (id),
    product_name text NOT NULL,
    default_quantity integer NOT NULL CHECK (default_quantity >= 0),
    selected_quantity integer NOT NULL CHECK (selected_quantity >= 0),
    unit varchar(16) NOT NULL CHECK (unit IN ('G', 'ML', 'UNIT')),
    extra_step_price numeric(10,2) NOT NULL CHECK (extra_step_price >= 0),
    extra_price numeric(10,2) NOT NULL CHECK (extra_price >= 0),
    UNIQUE (cart_item_id, dish_ingredient_id)
);
CREATE INDEX cart_item_ingredient_recipe_idx ON cart_item_ingredient (dish_ingredient_id);
CREATE INDEX cart_item_ingredient_product_idx ON cart_item_ingredient (product_id);
CREATE TABLE cart_item_addon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_item_id bigint NOT NULL REFERENCES cart_item (id),
    product_id bigint NOT NULL REFERENCES product (id),
    type varchar(16) NOT NULL CHECK (type IN ('DRINK', 'DESSERT')),
    product_name text NOT NULL,
    serving_format text NOT NULL,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    UNIQUE (cart_item_id, type)
);
CREATE INDEX cart_item_addon_product_idx ON cart_item_addon (product_id);
