name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 21 (Temurin LTS)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Verificar Formato (Spotless/Prettier)
      run: ./mvnw spotless:check

    - name: Levantar Base de Datos (Docker)
      run: docker compose up -d

    - name: Compilar y Testear (Build)
      run: ./mvnw clean verify

    - name: Compilar y Testear (Build)
      run: ./mvnw clean verify